apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - configmap.yaml
  - external-secret.yaml
  - deployment.yaml
  - worker-deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml
  - pdb.yaml
  - networkpolicy.yaml
